# NumPy Basics Practice Part-II
###### Arya Bhushan

![NumPy](https://i.morioh.com/a1380b1e61.png)

## Arithmetic operation in NumPy
- a + b | np.add(a,b)

- a - b | np.subtract(a,b)
- a * b | np.multiply(a,b)
- a / b | np.divide(a,b)
- a % b | np.mod(a,b)
- a ** b | np.power(a,b)
- 1/b | np.reciprocal(a)

In [1]:
import numpy as np

### add() / addition

In [25]:
#Adding 2 variables
var1 = np.array([1,2,3,4,5])
var2 = np.array([2,3,4,5,6])
varadd = var1 + var2
print(varadd)

[ 3  5  7  9 11]


In [9]:
#Adding number to a variable
varadd1 = var1 + 3
print(varadd1)

[4 5 6 7 8]


In [11]:
#Adding 2 variables using add function
var3 = np.array([1,2,3,4,5])
var4 = np.array([2,3,4,5,6])
varadd1 = np.add(var3,var4)
print(varadd1)

[ 3  5  7  9 11]


In [13]:
#Adding number to a variable using add function
varadd12 = var3 + 3
print(varadd12)

[4 5 6 7 8]


In [22]:
# Addition of 2-D array
var2da = np.array([[1,2,3],[1,2,3]])
var2db = np.array([[1,2,3],[1,2,3]])
varadd21 = np.add(var2da,var2db)
print(var2da)
print()
print(var2db)
print()
print('result: ',varadd21)

[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]]

result:  [[2 4 6]
 [2 4 6]]


### subtract() / subtraction

In [24]:
#Subtracting 2 variables
svar1 = np.array([1,2,3,4,5])
svar2 = np.array([2,3,4,5,6])
varsub = svar1 - svar2
print(varsub)

[-1 -1 -1 -1 -1]


In [26]:
#Subtracting number to a variable
varsub2 = svar1 - 3
print(varsub2)

[-2 -1  0  1  2]


In [27]:
# Subtraction of 2-D array
svar2da = np.array([[1,2,3],[1,2,3]])
svar2db = np.array([[1,2,3],[1,2,3]])
varsub21 = np.subtract(svar2da,svar2db)
print(svar2da)
print()
print(svar2db)
print()
print('result: ',varsub21)

[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]]

result:  [[0 0 0]
 [0 0 0]]


### multiply() / multiplication

In [28]:
mul1 = np.array([2,2,2])
mulres = np.multiply(mul1,3)
print(mulres)

[6 6 6]


In [32]:
mul2 = np.array([[1,2],[1,2]])
mul3 = np.array([[2,2],[2,2]])
mulres1 = np.multiply(mul2,mul3)
print(mul2)
print()
print(mul3)
print()
print('multiplication of result:')
print(mulres1)

[[1 2]
 [1 2]]

[[2 2]
 [2 2]]

multiplication of result:
[[2 4]
 [2 4]]


### divide() / division

In [33]:
div1 = np.array([33,45,66,27,81])
divres = np.divide(div1,3)
print('result after division')
print()
print(divres)

result after division

[11. 15. 22.  9. 27.]


### mod() / modulo

In [36]:
mod1 = np.array([33,45,66,27,81])         #output is remainder
modres = np.mod(mod1,7)
print('result')
print()
print(modres)

result

[5 3 3 6 4]


### power() / power or order

In [37]:
pow1 = np.array([[2,3,4],[5,6,7]])
powres = np.power(pow1,2)
print('result')
print()
print(powres)

result

[[ 4  9 16]
 [25 36 49]]


### reciprocal() 

In [39]:
rec = ([[1/2,1/3],[1/4,1/5]])
recres = np.reciprocal(rec)
print(recres)

[[2. 3.]
 [4. 5.]]


## More Arithmetic Functions in NumPy
- np.min(x) - Minimum
- np.max(x) - Maximum
- np.argmin(x) - Index of minimum
- np.argmax(x) - Index of Maximum
- np.sqrt(x) - Square root
- np.sin(x) - trigonometric sin
- np.cos(x) - trigonometric cos
- np.cumsum(x) - cummulative sum

### Maximum - np.max()

In [41]:
# for 1-D array
varmax = ([21,23,4,32,33,45,66,76,766,])
maxi = np.max(varmax)
print('Maximum: ',maxi)

Maximum:  766


In [42]:
# for 2-D array-column wise, axis =0
varmax1 = ([[23,45,27],[48,37,89]])
print('Maximum column wise: ', np.max(varmax1, axis = 0))

Maximum column wise:  [48 45 89]


In [44]:
# for 2-D array-row wise, axis =1
varmax2 = ([[23,45,27],[48,37,89]])
print('Maximum row wise: ', np.max(varmax2, axis = 1))

Maximum row wise:  [45 89]


### Minimum - np.min()

In [46]:
# for 1-D array
varmin = ([21,23,4,32,33,45,66,76,766,])
mini = np.min(varmin)
print('Minimum: ',mini)

Minimum:  4


In [47]:
# for 2-D array-column wise, axis =0
varmin1 = ([[23,45,27],[48,37,89]])
print('Minimum column wise: ', np.min(varmin1, axis = 0))

Minimum column wise:  [23 37 27]


In [49]:
# for 2-D array-column wise, axis =0
varmin2 = ([[23,45,27],[48,37,89]])
print('Minimum row wise: ', np.min(varmin2, axis = 1))

Minimum row wise:  [23 37]


### np.argmax()

In [53]:
varmax = ([21,23,4,32,33,45,66,76,766,])
maxi = np.max(varmax)
print('Maximum: ',maxi)
print('index number: ', np.argmax(varmax))

Maximum:  766
index number:  8


### np.argmin()

In [54]:
varmin = ([21,23,4,32,33,45,66,76,766,])
mini = np.min(varmin)
print('Minimum: ',mini)
print('index number: ', np.argmin(varmin))

Minimum:  4
index number:  2


### Square root - np.sqrt()

In [62]:
sqr = np.array([9,81,4,625,400,64])
sqrrot = np.sqrt(sqr)
print(f'the square root of {sqr} is ',sqrrot)

the square root of [  9  81   4 625 400  64] is  [ 3.  9.  2. 25. 20.  8.]


### np.sin(x)

In [66]:
sina = np.array([0,0.5235,0.7854,1.047,1.57])  #this takes angle in radian
print(np.sin(sina))     # sin (0) = 0 sin(1.57)= 1

[0.         0.49991446 0.70710808 0.86592661 0.99999968]


### np.cos(x)

In [68]:
cosa = np.array([0,0.5235,0.7854,1.047,1.57])  
print(np.cos(cosa))     # cos(0)=1, cos(1.57)= 0

[1.00000000e+00 8.66074787e-01 7.07105483e-01 5.00171075e-01
 7.96326711e-04]


### Cummulative sum - np.cumsum()

In [70]:
cuml = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
print(np.cumsum(cuml))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


## Shape and Reshape of Array

### shape

In [71]:
sh = np.array([[1,3,5,6],[2,4,5,7]])
print(sh.shape)

(2, 4)


In [74]:
#printing the column and row separately using index of shape as a list
print(sh)
print('number of rows: ',sh.shape[0])
print('number of columns: ',sh.shape[1])

[[1 3 5 6]
 [2 4 5 7]]
number of rows:  2
number of columns:  4


In [76]:
#shape of a n-D array
shn = np.array([1,2,3,4,5], ndmin = 8)
print('shape: ',shn.shape)

shape:  (1, 1, 1, 1, 1, 1, 1, 5)


### reshape

In [79]:
rsh = np.array([1,2,2,3,4,6])
#while reshaping take care that number of elements in both the arrays are same
rsh1 = rsh.reshape(3,2)
print(rsh)
print()
print(rsh1)

[1 2 2 3 4 6]

[[1 2]
 [2 3]
 [4 6]]


In [85]:
#lets check the dimension and shape of the above two array rsh and rsh1
print('shape of rsh: ',rsh.shape)
print('shape of rsh1: ',rsh1.shape)
print('dimension of rsh: ',rsh.ndim)
print('dimension of rsh1: ',rsh1.ndim)

shape of rsh:  (6,)
shape of rsh1:  (3, 2)
dimension of rsh:  1
dimension of rsh1:  2


In [86]:
#convert 2d array to 1d array
rsh2 = rsh1.reshape(-1)
print(rsh2)
print('dimension of rsh2: ',rsh2.ndim)

[1 2 2 3 4 6]
dimension of rsh2:  1


## The END