# NumPy Basics Practice Part1

![logo](https://www.brussellakeparagon.com/dev/ai-ml/numpy.png)

In [1]:
import numpy as np

## Importance of Numpy in pyhton
- Wide Variety of mathematical operations on arrays
- It supplies an enormous library of high level mathematical functions that operate on these arrays and matrices.
- Mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier Transforms, basic linear algebra, basic statistical operations, random simulation and much more.


### NumPy Vs Pyhton Lists speed comparison

In [7]:
%timeit [j**4 for j in range(1,9)]

1.12 µs ± 92.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
%timeit np.arange(1,9)**4

2.33 µs ± 37 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Creating a NumPy array

In [12]:
#direct
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [13]:
#using a list
a = ([1,2,3,4,4,4,5,5])
y = np.array(a)
print(a)
print(type(a))
print(y)
print(type(y))


[1, 2, 3, 4, 4, 4, 5, 5]
<class 'list'>
[1 2 3 4 4 4 5 5]
<class 'numpy.ndarray'>


### Create a program to take a list from user and print it as an array

In [15]:
lis = []
for i in range (1,5):
    n = int(input('Enter number in list: '))
    lis.append(n)
print(np.array(lis))

Enter number in list: 55
Enter number in list: 55
Enter number in list: 55
Enter number in list: 55
[55 55 55 55]


### 1-D array

In [30]:
a1 = np.array([1,2,3,4])
print(a1)
print(a1.ndim)

[1 2 3 4]
1


### 2-D array

In [31]:
a2 = np.array([[1,3,5,7],[2,4,6,8]])
print(a2)
print(a2.ndim)

[[1 3 5 7]
 [2 4 6 8]]
2


In [40]:
ab2 = np.array([[1,2,3,4,5]])
print(ab2)
print(ab2.ndim)

[[1 2 3 4 5]]
2


### 3-D array

In [38]:
a3 = np.array([[[1,2,4,5],[3,5,3,7],[4,6,2,8]]])
print(a3)
print(a3.ndim)

[[[1 2 4 5]
  [3 5 3 7]
  [4 6 2 8]]]
3


In [42]:
ab3 = np.array([[[1,4,3,6]]])        # count the number of '[[' for dimension
print(ab3)
print(ab3.ndim)

[[[1 4 3 6]]]
3


### N-D array

In [70]:
an = np.array([1,2,3,4],ndmin = 10)
print(an)
print(an.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [47]:
an = np.array([1,2,3,4],ndmin = 33)      #maximum allowable dimension is 32
print(an)
print(an.ndim)

ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)

In [ ]:
nib = [1,3,4,5]


### Array filled with 0's

In [49]:
# method 1
ar_zeros = np.zeros(4)
print(ar_zeros)

[0. 0. 0. 0.]


In [50]:
#method 2
ar_zeros1 = np.zeros(shape = (2,2), dtype = np.int32)
print(ar_zeros1)

[[0 0]
 [0 0]]


In [51]:
ar_zeros2 = np.zeros(shape = (3,4), dtype = np.int32)
print(ar_zeros2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [57]:
ar_zeros3 = np.zeros((3,3,3))
print(ar_zeros3)
print(ar_zeros3.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3


### Array filled with 1's

In [52]:
ar_one = np.ones(3)
print(ar_one)

[1. 1. 1.]


In [62]:
ar_ones = np.ones(shape = (2,3), dtype = np.int8)
print(ar_ones)
print(ar_ones.ndim)
print(ar_ones.dtype)

[[1 1 1]
 [1 1 1]]
2
int8


In [64]:
ar_one1 = np.ones((4,4))
print(ar_one1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Create an empty array

In [65]:
ar_em = np.empty(4)            # will return the last 1-D element with 4 elements here 
print(ar_em)

[0. 0. 0. 0.]


### An array with  a range of elements

In [66]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [69]:
ar_rn1 = np.arange(21)
print(ar_rn1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### Identity Matrix

In [71]:
ar_diag = np.eye(3)
print(ar_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
ar_diag1 = np.eye(5, dtype = np.int8)
print(ar_diag1)
print(ar_diag1.ndim)
print(ar_diag1.dtype)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
2
int8


In [84]:
ar_diag2 = np.eye(3,5, dtype = np.float_)           #default float is float64
print(ar_diag2)
print(ar_diag2.dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
float64


### Create an array with values that are spaced linearly in a specified interval

In [85]:
ar_lin = np.linspace(0,20, num = 5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [99]:
ar_lin1 = np.linspace (0,30, num = 10)
print(ar_lin1)

[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.        ]


## How to Create NumPy arrays with Random Numbers

### rand() - the function is used to generate a random value which belongs to  [0,1)

In [100]:
# 1-D
var = np.random.rand(4)
print(var)

[0.91518447 0.21825013 0.02402896 0.19146381]


In [101]:
# 2-D
var1 = np.random.rand(3,5)
print(var1)

[[0.53502544 0.9469999  0.53777308 0.84616537 0.67508001]
 [0.29804076 0.51468114 0.02151206 0.70243712 0.86145282]
 [0.3997298  0.55569376 0.93421149 0.15519315 0.52757512]]


In [108]:
# Random number generated
var2 = np.random.rand(3,5)
print(var2)

[[0.24395828 0.5140053  0.62680483 0.4598231  0.63224503]
 [0.25606753 0.47267375 0.84470543 0.11284904 0.75600713]
 [0.20679452 0.41877352 0.85999851 0.45701681 0.27012917]]


In [109]:
#3-D array
var3 = np.random.rand(2,3,2)
print(var3)

[[[0.14477505 0.66435365]
  [0.70226968 0.77512109]
  [0.66663268 0.92033263]]

 [[0.92079808 0.15727778]
  [0.12566931 0.41601901]
  [0.47043899 0.27641336]]]


### randn() -  to generate random numbers from a standard normal distribution, also known as a Gaussian distribution. This distribution has a bell-shaped curve with a mean of 0 and a standard deviation of 1

In [112]:
#1-D
varr = np.random.randn(5)
print(varr)

[ 2.67281413 -0.60546334  0.46022297  0.9440379   0.13337923]


In [117]:
#2-D
vart = np.random.randn(3,3)
print(vart)

[[-1.31015882 -0.41573936 -0.73547543]
 [ 1.0916115   1.25437912  0.92969482]
 [-0.06929114 -0.34186422  0.89511053]]


In [114]:
#3-D
vara = np.random.randn(3,3,3,)
print(vara)

[[[ 0.8853947  -1.56818751  2.02186427]
  [-1.08643588 -0.73033061 -2.43774342]
  [-0.65254583  0.7693218   1.69004022]]

 [[ 0.60274896  0.16045669 -0.84795756]
  [ 0.36207126 -1.73653233  0.48052994]
  [ 0.47349423  0.37138243  0.05318705]]

 [[-1.7494485   0.37203937  0.47486092]
  [-0.33133164 -1.53559577 -0.08858614]
  [-0.75249085  1.23373595 -0.12478699]]]


### ranf() -  an alias for the random_sample() function. Generate random floating-point numbers uniformly distributed between 0 (inclusive) and 1 (exclusive)

In [120]:
fir = np.random.ranf(3)
print(fir)

[0.04959221 0.97776575 0.40923385]


In [121]:
fir1 = np.random.random_sample(4)
print(fir1)

[0.84736684 0.44276678 0.33844961 0.21869746]


### randint() - the function is used to generate a random number between a given range

In [125]:
varn1 = np.random.randint(1,20,4)
print(varn1)

[19 18 15 15]


In [126]:
varn2 = np.random.randint(5,20,5)
print(varn2)

[14 13 11 13  7]


## Changing datatypes of numpy arrays

In [133]:
#asigning datatypes
lisa = np.array([1,3,5,3,5,6,8])          #default
print('Data types of lisa: ',lisa.dtype)
lisa1 = np.array([2,3,4,5,3,5,3,4], dtype = np.float_)           #set to default float
print('Data types of lisa1: ',lisa1.dtype)

Data types of lisa:  int32
Data types of lisa1:  float64


In [136]:
#changing datatypes
nw1 = np.array([2,35,4,5,5,5,6])
nw2 = np.float32(nw1)
print('Data types of nw1: ',nw1.dtype)
print('Data types of nw2: ',nw2.dtype)

Data types of nw1:  int32
Data types of nw2:  float32


In [142]:
#changing datatype by astype function
nw3 = np.array([1,2,3,4,5,7])
nw4 = nw3.astype(float)
print('Data types of nw3: ',nw3.dtype)
print('Data types of nw4: ',nw4.dtype)

Data types of nw3:  int32
Data types of nw4:  float64
float64


In [143]:
print(nw3.astype(float).dtype)

float64


## THE END